[mypy]

python_version = 3.12

warn_return_any = True
warn_unused_configs = True

disallow_untyped_defs = True
disallow_any_generics = False

check_untyped_defs = True

ignore_missing_imports = True

strict_optional = True

show_error_codes = True

pretty = True

namespace_packages = True